//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public double Sl { get; set; }
        public Nullable<double> Marital_Status { get; set; }
        public Nullable<double> Gender { get; set; }
        public Nullable<double> Religion { get; set; }
        public Nullable<double> Age { get; set; }
        public Nullable<double> Occupation { get; set; }
        public Nullable<double> Education { get; set; }
        public Nullable<double> CL1 { get; set; }
        public Nullable<double> CL2 { get; set; }
        public Nullable<double> CL3 { get; set; }
        public Nullable<double> CL4 { get; set; }
        public Nullable<double> CL5 { get; set; }
        public Nullable<double> CL6 { get; set; }
        public Nullable<double> FL1 { get; set; }
        public Nullable<double> FL2 { get; set; }
        public Nullable<double> FL3 { get; set; }
        public Nullable<double> FL4 { get; set; }
        public Nullable<double> FL5 { get; set; }
        public Nullable<double> FL6 { get; set; }
        public Nullable<double> PL1 { get; set; }
        public Nullable<double> PL2 { get; set; }
        public Nullable<double> PL3 { get; set; }
        public Nullable<double> PL4 { get; set; }
        public Nullable<double> PL5 { get; set; }
        public Nullable<double> PL6 { get; set; }
        public Nullable<double> SL1 { get; set; }
        public Nullable<double> SL2 { get; set; }
        public Nullable<double> SL3 { get; set; }
        public Nullable<double> SL4 { get; set; }
        public Nullable<double> SL5 { get; set; }
        public Nullable<double> SL6 { get; set; }
        public Nullable<double> HSL1 { get; set; }
        public Nullable<double> HSL2 { get; set; }
        public Nullable<double> HSL3 { get; set; }
        public Nullable<double> HSL4 { get; set; }
    }
}
